/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mayi_jni_l3_JNILib */

#ifndef _Included_com_mayi_jni_l3_JNILib
#define _Included_com_mayi_jni_l3_JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mayi_jni_l3_JNILib
 * Method:    init
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_com_mayi_jni_1l3_JNILib_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_mayi_jni_l3_JNILib
 * Method:    readAsset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mayi_jni_1l3_JNILib_readAsset
  (JNIEnv *, jclass);

/*
 * Class:     com_mayi_jni_l3_JNILib
 * Method:    CameraDevice_init
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mayi_jni_1l3_JNILib_CameraDevice_1init
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_mayi_jni_l3_JNILib
 * Method:    CameraDevice_start
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mayi_jni_1l3_JNILib_CameraDevice_1start
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_mayi_jni_l3_JNILib
 * Method:    CameraDevice_stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mayi_jni_1l3_JNILib_CameraDevice_1stop
  (JNIEnv *, jclass);

/*
 * Class:     com_mayi_jni_l3_JNILib
 * Method:    newFrameAvailable
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_com_mayi_jni_1l3_JNILib_newFrameAvailable
  (JNIEnv *, jclass, jint, jint, jbyteArray);

/*
 * Class:     com_mayi_jni_l3_JNILib
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mayi_jni_1l3_JNILib_step
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
